common:
  img_topic: "/camera/image_color"
  lid_topic: "/livox/lidar"
  imu_topic: "/livox/imu"
  img_en: 1
  lidar_en: 1
  ros_driver_bug_fix: false

extrin_calib:
  extrinsic_T: [-0.011, -0.02329, 0.04412]
  extrinsic_R: [1, 0, 0, 0, 1, 0, 0, 0, 1]
  Rcl: [ -0.002043, -0.999998,  0.000327,
        0.379870, -0.001079, -0.925039,
        0.925038, -0.001765,  0.379871]
  Pcl: [  0.017663, -0.087666,  0.033230]

time_offset:
  imu_time_offset: 0.0
  img_time_offset: 0.1
  exposure_time_init: 0.0

preprocess:
  point_filter_num: 8      # 进一步加大过滤：极其粗糙但快
  filter_size_surf: 0.8    # 叶子节点保持0.8或1.0
  lidar_type: 1 # Livox Avia/Mid360
  scan_line: 6
  blind: 0.5
  feature_extract_enabled: false

vio:
  max_iterations: 2        # VIO 极限两次迭代
  outlier_threshold: 1000 
  img_point_cov: 100 
  patch_size: 4            # 光流追踪块进一步减小为4x4
  patch_pyrimid_level: 2   # 图像金字塔只用2层
  normal_en: false         # 关闭面片法向量估计（极其节省CPU）
  raycast_en: false
  inverse_composition_en: false
  exposure_estimate_en: false
  inv_expo_cov: 0.1
  grid_size: 40            # 网格进一步拉大，提取极少量的视觉特征

imu:
  imu_en: true
  imu_int_frame: 30
  acc_cov: 0.8 # 0.2
  gyr_cov: 0.5 # 0.5
  b_acc_cov: 0.001 # 0.1
  b_gyr_cov: 0.001 # 0.1
  gravity_est_en: false    # 关闭重力自适应估计
  ba_bg_est_en: false      # 关闭零偏估计，降低状态量维度带来的协方差计算

lio:
  max_iterations: 3        # LIO 极限三次配准
  dept_err: 0.02
  beam_err: 0.15
  min_eigen_value: 0.015   
  voxel_size: 1.0          # 体素建图拉大到1.0m
  max_layer: 1             # iKd-Tree或VoxelMap的最大层级降到1
  max_points_num: 30       # 体素内保留最大点数减小
  layer_init_num: [3, 3, 3, 3, 3]

local_map:
  map_sliding_en: false
  half_map_size: 100
  sliding_thresh: 8

uav:
  imu_rate_odom: false
  gravity_align_en: true

publish:
  dense_map_en: false
  pub_effect_point_en: false
  pub_plane_en: false
  pub_scan_num: 1
  blind_rgb_points: 0.0

evo:
  seq_name: "CBD_Building_01"
  pose_output_en: false

pcd_save:
  pcd_save_en: false
  colmap_output_en: false  # 必须关闭以节省 IO 时间
  filter_size_pcd: 0.5
  interval: -1
